[package]
name = "ii-greetd-launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
ii-greetd-config = { path = "../config" }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
